<template>
    <div class="row col-md-10">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <h4>Tìm kiếm tag</h4>
                        <div
                            class="search input-group float-md-start w-50 search-admin"
                        >
                            <input
                                type="text"
                                class="form-control shadow-none"
                                name="name"
                                placeholder="Nhập tên tag"
                            />
                            <button
                                class="btn btn-success btn--search-color"
                                type="submit"
                                title="searchButton"
                            >
                                <i
                                    class="fa-solid fa-magnifying-glass search__btn--icons"
                                ></i>
                            </button>
                        </div>
                </div>
                <div class="col-md-12">
                    <h4>Quản lý tag</h4>
                </div>
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table border mb-0 table-striped">
                            <thead class="table-dark fw-semibold">
                                <tr class="align-middle">
                                    <th>Mã thẻ</th>
                                    <th>Tên thẻ</th>
                                    <th>Đường dẫn</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="list-tags">
                                <tr class="align-middle"
                                v-for="(item, index) in tags"
                                :key="index">
                                    <td>
                                        <div>{{item.TagId}}</div>
                                    </td>
                                    <td>
                                        <div>{{item.TagName}}</div>
                                    </td>
                                    <td>
                                        <div>{{item.Slug}}</div>
                                    </td>
                                    <td>
                                        <div class="dropstart">
                                            <button
                                                class="btn btn-primary"
                                                type="button"
                                                @click="editTag(item.TagId)"
                                            >
                                                Edit
                                            </button>
                                            <button
                                                class="btn btn-danger"
                                                type="button"
                                                @click="deleteTag(item.TagId)"
                                            >
                                                Delete
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="box-footer">
                        <div class="box-footer-clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 config-box">

                <div class="col-md-12">
                    <h4>Chỉnh sửa tag</h4>
                </div>
                <div class="col-12">
                    <label for="inputMaTheLoai" class="form-label"
                        >Mã tag</label
                    >
                    <input
                        type="text"
                        name="TagId"
                        class="form-control"
                        id="inputMaTheLoai"
                        placeholder="Id autogenerated"
                        readonly
                        v-model="tag.TagId"
                    />
                </div>
                <div class="col-12">
                    <label for="inputTenTheLoai" class="form-label"
                        >Tên tag</label
                    >
                    <input
                        type="text"
                        name="TagName"
                        class="form-control"
                        id="inputTenTheLoai"
                        v-model="tag.TagName"
                    />
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">
                        Lưu thay đổi
                    </button>
                </div>

        </div>
    </div>
</template>

<script>
import axios from "axios";
const env = process.env;

export default {
    name: "admintag-layout",
    data(){
        return{
            tags: [],
            tag_state: "Thêm",
            tag: {
                "TagId": null,
                "TagName": "",
            },
        }
    },
    created() {
        this.getTags();
    },
    methods: {
        async getTags() {
            try {
                let url = `${env.VUE_APP_API_KEY}/tag/get-all`;
                let res = (await axios.get(url)).data.Data;
                this.tags = res;
                console.log(this.tags)
            } catch (e) {
                console.log(e);
            }
        },
        async editTag(id){
            this.tag_state = "Chỉnh sửa";
            try {
                let url = `${env.VUE_APP_API_KEY}/tag/get-by-id?id=` + id;
                let res = (await axios.get(url)).data;
                this.tag.TagId = res.TagId;
                this.tag.TagName = res.TagName;
                console.log(res)
            } catch (e) {
                console.log(e);
            }
        },
        async deleteTag(id){
            try {
                if (id == this.tag.TagId){
                    this.tag_state = "Thêm";
                }
                let url = `${env.VUE_APP_API_KEY}/tag/delete?id=` + id;
                await axios.delete(url);
                this.getTags();
            } catch (e) {
                console.log(e);
            }
        },
        async saveChange(){
            try {
                let url = `${env.VUE_APP_API_KEY}/tag/${this.tag.tagId == null ? "add" : "update"}`;
                let header = {
                    Authorization : 'Bearer ' + localStorage.getItem(env.JWT_API_KEY)
                }
                axios.post(url, this.tag, header);
                console.log(header)
                console.log(this.tag)
                this.getTags();
            } catch (e) {
                console.log(e);
            }
        },
    }
};
</script>

<style>
.config-box > .col-12 {
    margin-bottom: 1rem;
}
</style>
